### ISSUE TITLE
SOMETHING is failing to add roles. 

### ISSUE THREAD

**Issue by User-r00** [User-r00/bravetraveler-issues#13]
**Describe the bug**
I can't see what it is just yet but something is throwing an exception.

Traceback (most recent call last):
  File "/home/soteria/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/soteria/src/bravetraveler/extensions/remindme.py", line 79, in remindme_command
    number = int(number)
ValueError: invalid literal for int() with base 10: 'in'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/soteria/.local/lib/python3.6/site-packages/discord/client.py", line 251, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 129, in on_message
    roles = message.author.roles
AttributeError: 'User' object has no attribute 'roles'

**Comment by User-r00** [comment]
Fixed in https://github.com/User-r00/bravetraveler/pull/25.

**Comment by User-r00** [comment]
Merged to master.

**Comment by User-r00** [comment]
Pushed too server.
